annotated-types==0.6.0
anyio==3.7.1
beautifulsoup4==4.12.2
bs4==0.0.1
certifi==2023.7.22
chardet==5.2.0
charset-normalizer==3.3.2
contourpy==1.2.0
cycler==0.12.1
distro==1.8.0
fonttools==4.45.0
h11==0.14.0
httpcore==1.0.1
httpx==0.25.1
idna==3.4
kiwisolver==1.4.5
lxml==4.9.3
matplotlib==3.8.2
numpy==1.26.2
openai==1.1.1
packaging==23.2
pandas==2.1.3
Pillow==10.1.0
pydantic==2.4.2
pydantic_core==2.10.1
pyparsing==3.1.1
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
regex==2023.10.3
requests==2.31.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
tiktoken==0.5.1
tqdm==4.66.1
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
